export const ErrorCode = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  HTTP_EXCEPTION: "HTTP_EXCEPTION",
  CONFLICT: "CONFLICT",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  MISSING_WORKSPACE_HEADER: "MISSING_WORKSPACE_HEADER",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  NOT_WORKSPACE_MEMBER: "NOT_WORKSPACE_MEMBER",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",

  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_NOT_FOUND_OR_ACCESS_DENIED: "TEAM_NOT_FOUND_OR_ACCESS_DENIED",
  TEAM_NOT_FOUND_OR_NOT_MEMBER: "TEAM_NOT_FOUND_OR_NOT_MEMBER",
  NOT_TEAM_MEMBER: "NOT_TEAM_MEMBER",
  NOT_MEMBER_OF_THIS_TEAM: "NOT_MEMBER_OF_THIS_TEAM",
  TEAM_KEY_ALREADY_EXISTS: "TEAM_KEY_ALREADY_EXISTS",

  ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
  ISSUES_NOT_ACCESSIBLE: "ISSUES_NOT_ACCESSIBLE",
  PREVIOUS_AND_NEXT_ISSUES_MUST_BE_DIFFERENT: "PREVIOUS_AND_NEXT_ISSUES_MUST_BE_DIFFERENT",
  PREVIOUS_ISSUE_NOT_IN_TARGET_COLUMN: "PREVIOUS_ISSUE_NOT_IN_TARGET_COLUMN",
  NEXT_ISSUE_NOT_IN_TARGET_COLUMN: "NEXT_ISSUE_NOT_IN_TARGET_COLUMN",
  TARGET_COLUMN_REQUIRES_ADJACENT_ISSUE: "TARGET_COLUMN_REQUIRES_ADJACENT_ISSUE",
  UNABLE_TO_DETERMINE_ISSUE_SORT_ORDER: "UNABLE_TO_DETERMINE_ISSUE_SORT_ORDER",

  LABEL_NOT_FOUND: "LABEL_NOT_FOUND",
  LABEL_NAME_ALREADY_EXISTS: "LABEL_NAME_ALREADY_EXISTS",

  ISSUE_SPRINT_NOT_FOUND: "ISSUE_SPRINT_NOT_FOUND",
  TARGET_SPRINT_NOT_FOUND: "TARGET_SPRINT_NOT_FOUND",
  CANNOT_START_ARCHIVED_SPRINT: "CANNOT_START_ARCHIVED_SPRINT",
  CANNOT_START_COMPLETED_SPRINT: "CANNOT_START_COMPLETED_SPRINT",
  SPRINT_ALREADY_ACTIVE: "SPRINT_ALREADY_ACTIVE",
  CANNOT_START_WHILE_SPRINT_ACTIVE: "CANNOT_START_WHILE_SPRINT_ACTIVE",
  CANNOT_UPDATE_ARCHIVED_SPRINT: "CANNOT_UPDATE_ARCHIVED_SPRINT",
  CANNOT_UPDATE_COMPLETED_SPRINT: "CANNOT_UPDATE_COMPLETED_SPRINT",
  CANNOT_COMPLETE_ARCHIVED_SPRINT: "CANNOT_COMPLETE_ARCHIVED_SPRINT",
  SPRINT_ALREADY_COMPLETED: "SPRINT_ALREADY_COMPLETED",
  ONLY_ACTIVE_SPRINTS_CAN_BE_COMPLETED: "ONLY_ACTIVE_SPRINTS_CAN_BE_COMPLETED",
  SPRINT_NOT_CURRENTLY_ACTIVE: "SPRINT_NOT_CURRENTLY_ACTIVE",
  TARGET_SPRINT_MUST_BE_PLANNED: "TARGET_SPRINT_MUST_BE_PLANNED",
  SPRINT_ALREADY_ARCHIVED: "SPRINT_ALREADY_ARCHIVED",
  CANNOT_ARCHIVE_ACTIVE_SPRINT: "CANNOT_ARCHIVE_ACTIVE_SPRINT",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  NO_AVATAR_FILE_PROVIDED: "NO_AVATAR_FILE_PROVIDED",
  ONLY_IMAGE_FILES_SUPPORTED: "ONLY_IMAGE_FILES_SUPPORTED",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  FAILED_TO_CHANGE_PASSWORD: "FAILED_TO_CHANGE_PASSWORD",

  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  ATTACHMENT_FILE_NOT_FOUND: "ATTACHMENT_FILE_NOT_FOUND",
  FILE_MISSING_OR_INVALID: "FILE_MISSING_OR_INVALID",

  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",

  INVITATION_NOT_FOUND_OR_EXPIRED: "INVITATION_NOT_FOUND_OR_EXPIRED",

  DURATION_MUST_BE_POSITIVE: "DURATION_MUST_BE_POSITIVE",
  TIME_ENTRY_NOT_FOUND: "TIME_ENTRY_NOT_FOUND",

  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
} as const;

export type ApiErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
